# Generated by Django 2.1.4 on 2018-12-09 19:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_created=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('numero', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_movimento', models.CharField(choices=[('en', 'Entrada'), ('sd', 'Saída')], default='sd', max_length=2)),
                ('motivo_movimento', models.CharField(choices=[('vd', 'Venda'), ('cp', 'Compra para revenda'), ('dv', 'Cancelamento de venda'), ('ou', 'Outros')], default='vd', max_length=2)),
                ('quantidade', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Movimento do estoque',
                'verbose_name_plural': 'Movimento do estoque',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30, unique=True)),
                ('descricao', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('estoque', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.Produto'),
        ),
    ]
