# Generated by Django 2.1.4 on 2018-12-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueentrada',
            name='entrada',
            field=models.CharField(choices=[('dv', 'Compra'), ('dv', 'Cancelamento de venda'), ('ou', 'Outros')], default='dv', max_length=2),
        ),
        migrations.AddField(
            model_name='estoquesaida',
            name='saida',
            field=models.CharField(choices=[('vd', 'Venda'), ('df', 'Devolução para fábrica'), ('ou', 'Outros')], default='vd', max_length=2),
        ),
    ]
