# Generated by Django 2.1.4 on 2018-12-09 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_categoriaproduto_subcategoriaproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='subcategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='estoque.SubCategoriaProduto'),
            preserve_default=False,
        ),
    ]
