# Generated by Django 2.1.4 on 2018-12-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('estoque', '0003_auto_20181209_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_created=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('numero', models.CharField(max_length=30)),
                ('tipo_movimento', models.CharField(choices=[('en', 'Entrada'), ('sd', 'Saída')], default='sd', max_length=2)),
                ('motivo_movimento', models.CharField(choices=[('vd', 'Venda'), ('cp', 'Compra para revenda'), ('dv', 'Cancelamento de venda'), ('ou', 'Outros')], default='vd', max_length=2)),
                ('quantidade', models.IntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.Produto')),
            ],
            options={
                'verbose_name': 'Saída do estoque',
                'verbose_name_plural': 'saída do estoque',
            },
        ),
        migrations.RemoveField(
            model_name='estoqueentrada',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='estoquesaida',
            name='produto',
        ),
        migrations.DeleteModel(
            name='EstoqueEntrada',
        ),
        migrations.DeleteModel(
            name='EstoqueSaida',
        ),
    ]
