# Generated by Django 2.1.4 on 2018-12-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_auto_20181209_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentoestoque',
            options={'verbose_name': 'Movimento do estoque', 'verbose_name_plural': 'Movimento do estoque'},
        ),
    ]
