# Generated by Django 2.1.4 on 2018-12-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_auto_20181209_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentoestoque',
            name='numero',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
