# Generated by Django 2.1.4 on 2018-12-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20181205_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='estoqueentrada',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='estoquesaida',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
