# Generated by Django 2.1.4 on 2018-12-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemvenda',
            old_name='qtde',
            new_name='quantidade',
        ),
    ]
