# Generated by Django 2.1.4 on 2018-12-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=30, unique=True)),
                ('sobrenome', models.CharField(max_length=30)),
                ('nascimento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
